spring:
  application:
    name: service-api
  ## 选择运行环境
  profiles:
    active: dev

## 公共配置 ##
server:
  port: 8762
  servlet:
    context-path: /api

#feign 的超时时间
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 20000

# jwt 配置
jwt:
  secret_key: ok332shyuasdf

# cache 配置
cache:
  millisecond: 7200000


# log 配置
logging:
  level:
    root: info
  file: ./logs/api.log

# mybatis 扫描路径
mybatis:
  mapper-locations: classpath:mapper/*.xml